server:
  port: 8080

spring:
  # regarding to mysql database configurations
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
      # ddl-auto: validate, in production environment.
    show-sql: false
    properties:
      hibernate:
        # explicitly setting mysql dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    # Disable the Javax Validation inside Spring Data JPA
    javax:
      persistence:
        validation:
          mode: none

  # Redis, environment variable
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # Flyway-mysql, tracking Database migration scripts.
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0

  # restricting max-size uploaded file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # config message follow Accept-Language ( header)
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

  # OAuth2.
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 119564257566-qjmpshhdei0uiioord9m3mi5bktg92g5.apps.googleusercontent.com
            client-secret: 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
            # register a page which google will redirect to, auth.callback component.
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:4200/auth/google/callback}"
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            client-id: 24244624138502522
            client-secret: 2715647e4e4cb08299f44992275dcef9
            # register a page which facebook will redirect to, auth.callback component.
            redirect-uri: "${FACEBOOK_REDIRECT_URI:http://localhost:4200/auth/facebook/callback}"
            auth-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)

# jwt
jwt:
  expiration: ${JWT_EXP:86400} #1 day = 24 * 60 * 60 = 86400
  expiration-refresh-token: ${REFRESH_JWT_EXP:604800} #7 days = 7 * 24 * 60 * 60
  secretKey: ${JWT_SECRET:jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4}

# prefix for api
api:
  prefix: /api/v1

# VNPAY
vnpay:
  payment-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  transaction-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
  # redirect to paymentCallback - Angular.
  return-payment-url: "${VNPAY_RETURN_URI:http://localhost:4200/payments/paymentCallback}"
  # register with arbitrary valid website in VNPAY and get below code.
  # not shopApp, a personal webside that's deployed and had a ssl certificate, Https://....
  tmn-code: "HAOYCDK8"
  secret-key: "AQFI8KD7VVSL68VK677YYSJB2BWKHWUO"























