server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimeZone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Disable the Javax Validation inside Spring Data JPA
    javax:
      persistence:
        validation:
          mode: none
  # restricting max-size uploaded file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # config message follow Accept-Language ( header)
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  # environment Redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
# api
api:
  prefix: api/v1
