
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Test@abc
      MYSQL_DATABASE: shopapp
    ports:
      - 3307:3306
    networks:
      - shopapp-network  # internal network.

  phpmyadmin8-container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container      
    ports:
      - "8100:80" #expose local: 8100, internal docker: 80
    environment:
      PMA_HOST: mysql8-container #phpMyAdmin Host, PMA = PHP My Amin
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - shopapp-network
  
  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data # directory mount.
    networks:
      - shopapp-network

networks:
  shopapp-network:
    name: shopapp-network
    driver: bridge

# command line about docker compose
# run manually sequence container.
  # docker-compose -f ./docker-compose.yml up -d mysql8-container
  # docker-compose -f ./docker-compose.yml up -d phpmyadmin8-container
  # docker-compose -f ./docker-compose.yml up -d redis-container

# run docker-compose
  # docker-compose up -d
  # docker-compose down -d
